server:
  port: 8081

spring:
  application:
    name: news-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/1809a?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
  data:
    mongodb:
      host: localhost
      port: 27017
      database: 1809a
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    pool:
    max-active: 20
    max-wait: -1
    max-idle: 8
    min-idle: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

