server:
  port: 80

spring:
  application:
    name: news-feign
    redis:
      host: localhost
      port: 6379
      timeout: 20000
      maxIdle: 300
      maxWaitMillis: 1000
      testOnBorrow: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
